<a href="https://colab.research.google.com/github/Gonza03s/intro-analisis-de-datos/blob/master/Manipulaci%C3%B3n_de_Datos_con_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulación y Análisis de Datos con Pandas
### Aplicado al Dataset del Titanic de Kaggle

---

## Introducción al Análisis de Datos

### ¿Qué es Pandas?

Pandas es una biblioteca de Python especializada en la manipulación, transformación y análisis de datos.

Mientras que NumPy está orientado al trabajo eficiente con datos numéricos en arrays, Pandas incorpora estructuras diseñadas para trabajar con datos similares a los que encontramos en un dataset real. Por ejemplo:

- pasajeros de un barco
- transacciones bancarias
- ventas de una tienda
- resultados de encuestas
- registros médicos
- datos meteorológicos

Una tabla puede contener:

- **filas** → registros u observaciones
- **columnas** → variables o características
- **valores** → información correspondiente a cada registro

La estructura principal de Pandas es el **DataFrame**: una tabla de datos que podemos manipular mediante Python.

### ¿Por qué Pandas es importante en Análisis de Datos?

Pandas permite realizar muchas de las tareas que aparecen habitualmente durante un análisis:

1. Cargar datos
2. Explorar un dataset
3. Comprender sus variables
4. Detectar valores faltantes
5. Seleccionar información
6. Filtrar registros
7. Crear nuevas variables
8. Transformar datos
9. Agrupar información
10. Calcular estadísticas
11. Ordenar resultados
12. Combinar datasets
13. Preparar los datos para visualizaciones
14. Obtener información que permita responder preguntas

Por eso Pandas ocupa un lugar central dentro del proceso de análisis de datos.

### Pandas y NumPy

Pandas está estrechamente relacionado con NumPy.

- **NumPy** → operaciones numéricas eficientes
- **Pandas** → manipulación y análisis de datos tabulares

NumPy trabaja muy bien con arrays como `[22, 38, 26, 35, 28]`, mientras que Pandas permite trabajar con información tabular como:

| PassengerId | Survived | Pclass | Name | Sex | Age | Fare | Embarked |
|---|---|---|---|---|---|---|---|
| 1 | 0 | 3 | Braund | male | 22 | 7.25 | S |
| 2 | 1 | 1 | Cumings | female | 38 | 71.28 | C |
| 3 | 1 | 3 | Heikkinen | female | 26 | 7.92 | S |

Esto se aproxima mucho más a los datasets que encontraremos en un análisis real.

### Dataset que utilizaremos: Titanic

Para aprender Pandas vamos a utilizar el clásico dataset del Titanic, disponible en Kaggle. Contiene información sobre los pasajeros del Titanic, incluyendo si sobrevivieron o no.

| Variable | Descripción |
|---|---|
| PassengerId | Identificador del pasajero |
| Survived | Supervivencia (0 = No, 1 = Sí) |
| Pclass | Clase del billete (1, 2, 3) |
| Name | Nombre del pasajero |
| Sex | Sexo (male / female) |
| Age | Edad en años |
| SibSp | Número de hermanos/cónyuges a bordo |
| Parch | Número de padres/hijos a bordo |
| Ticket | Número de billete |
| Fare | Tarifa pagada |
| Cabin | Número de cabina |
| Embarked | Puerto de embarque (C = Cherbourg, Q = Queenstown, S = Southampton) |

Nuestro objetivo no será simplemente aprender funciones de Pandas. Vamos a utilizar estas herramientas para responder preguntas sobre los datos, por ejemplo:

- ¿Cuántos pasajeros viajaban en el Titanic?
- ¿Cuántos sobrevivieron?
- ¿Cuál fue la tasa de supervivencia?
- ¿Cuál es la edad promedio de los pasajeros?
- ¿La clase influyó en la supervivencia?
- ¿Las mujeres tenían más probabilidades de sobrevivir?
- ¿Cuánto pagaron en promedio los pasajeros de primera clase?
- ¿Qué puerto de embarque tuvo más pasajeros?

De esta manera, Pandas se convierte en una herramienta para hacer **preguntas a los datos**.

## Importar Pandas

Para comenzar debemos importar la biblioteca. Utilizamos habitualmente `pd` como alias.

In [ ]:
import pandas as pd

## Cargar un dataset

Si nuestro dataset está almacenado en un archivo CSV podemos utilizar `read_csv()`, que permite leer un archivo CSV y convertirlo en un DataFrame. La variable `df` es una convención muy utilizada para representar un DataFrame.

> **¿Para qué le sirve al analista?** Esta función es fundamental porque permite llevar los datos desde un archivo hacia Python para comenzar a analizarlos. Sin este paso no tenemos los datos disponibles dentro de nuestro programa.

In [ ]:
df = pd.read_csv("/content/titanic.csv")

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## ¿Qué es un DataFrame?

Un DataFrame es una estructura tabular formada por filas, columnas e índices. Podemos pensarlo como una tabla de Excel, pero diseñada para ser manipulada mediante código.

```
             columnas
                ↓
        Survived   Age   Fare
        ------------------------
fila 0     0        22    7.25
fila 1     1        38    71.28
fila 2     1        26    7.92
        ↑
      índice
```

## Primer contacto con los datos

`head()` muestra las primeras filas del DataFrame (por defecto, 5).

> **¿Para qué le sirve al analista?** Permite realizar una primera inspección visual: comprobar si el archivo se cargó correctamente, cómo están organizadas las columnas, qué tipo de información contiene cada variable, si aparecen valores extraños.
>
> **Pregunta que responde:** «¿Cómo son mis datos?»

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

## Últimas filas

`tail()` muestra las últimas filas (por defecto, 5).

> **¿Para qué le sirve al analista?** Permite comprobar cómo terminan los datos y detectar posibles problemas al final del archivo.

In [ ]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Dimensiones del DataFrame

Una de las primeras preguntas que debemos responder es: «¿Cuántos registros tengo y cuántas variables?»

> **¿Para qué le sirve al analista?** `shape` permite conocer rápidamente el tamaño del dataset. Es importante porque antes de analizar debemos saber con qué cantidad de información estamos trabajando.
>
> **Preguntas que responde:** «¿Cuántos pasajeros viajaban en el Titanic?» / «¿Cuántas variables tengo disponibles?»

In [ ]:
df.shape

(891, 12)

### Cantidad de filas

> **¿Para qué le sirve al analista?** Permite conocer la cantidad de observaciones o registros disponibles. Por ejemplo: «Nuestro dataset contiene 891 pasajeros.»

In [ ]:
len(df)

891

In [ ]:
df.shape[0]

891

### Cantidad de columnas

> **¿Para qué le sirve al analista?** Permite conocer cuántas variables tenemos disponibles para analizar.

In [ ]:
df.shape[1]

12

## Nombres de las columnas

> **¿Para qué le sirve al analista?** Permite conocer qué variables están disponibles. Esto es fundamental antes de comenzar cualquier análisis: un analista primero debe conocer qué información tiene antes de decidir qué preguntas puede responder.

In [ ]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

## Información general del DataFrame

`info()` muestra cantidad de registros, nombres de columnas, cantidad de valores no nulos, tipos de datos y uso aproximado de memoria. En el Titanic veremos que `Age`, `Cabin` y `Embarked` tienen valores faltantes.

> **¿Para qué le sirve al analista?** Permite realizar un diagnóstico inicial del dataset: detectar valores faltantes, columnas numéricas, columnas de texto y posibles problemas de tipos.
>
> **Pregunta que responde:** «¿Cómo está estructurado mi dataset?»

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## Tipos de datos

> **¿Para qué le sirve al analista?** El tipo de dato determina qué operaciones podemos realizar sobre una variable. Por ejemplo, tiene sentido calcular `df["Age"].mean()`, pero no `df["Name"].mean()`, porque `Name` contiene texto.
>
> **Idea importante:** antes de analizar una variable debemos conocer qué representa y qué tipo de dato contiene.

In [ ]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

## Series

Una columna de un DataFrame de Pandas es una estructura llamada **Series**. Posee valores, índices, nombre y tipo de dato.

> **¿Para qué le sirve al analista?** La Series permite trabajar con una variable específica del dataset.

In [ ]:
edad = df["Age"]

## Seleccionar una columna

> **¿Para qué le sirve al analista?** Permite concentrarnos en una variable concreta.

In [ ]:
df["Sex"]

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [ ]:
df["Fare"]

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

## Seleccionar varias columnas

> **¿Para qué le sirve al analista?** Permite construir una vista más pequeña del dataset con las variables relevantes para una pregunta concreta. Por ejemplo: «Queremos estudiar la relación entre supervivencia, clase, sexo, edad y tarifa.» No necesitamos mostrar las 12 columnas.

In [ ]:
df[
    [
        "Survived",
        "Pclass",
        "Sex",
        "Age",
        "Fare"
    ]
]

     Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

## Diferencia entre Series y DataFrame

Cuando hacemos `df["Age"]` obtenemos una **Series**. Cuando hacemos `df[["Age"]]` obtenemos un **DataFrame**. Esto puede parecer una diferencia pequeña, pero es importante comprenderla.

In [ ]:
type(df["Age"])

pandas.core.series.Series

In [ ]:
type(df[["Age", "Sex"]])

pandas.core.frame.DataFrame

## Estadísticas descriptivas

`describe()` genera un resumen estadístico de las columnas numéricas: count, mean, std, min, percentiles, max.

> **¿Para qué le sirve al analista?** Permite obtener rápidamente una visión estadística general de las variables numéricas, en lugar de calcular manualmente cada estadística.
>
> **Preguntas que ayuda a responder:** «¿Cuál es la edad promedio de los pasajeros?» / «¿Cuál fue la tarifa mínima/máxima pagada?» / «¿Qué tan dispersas están las edades?»

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

## Analizar una variable numérica

### `mean()` — Promedio

> **¿Para qué le sirve al analista?** Permite obtener una medida de tendencia central. Por ejemplo: «La edad promedio de los pasajeros del Titanic era de aproximadamente 30 años.»

In [ ]:
df["Age"].mean()

np.float64(29.69911764705882)

### `median()` — Mediana

> **¿Para qué le sirve al analista?** Permite conocer el valor central de los datos y resulta especialmente útil cuando existen valores extremos.
>
> **Pregunta:** «¿Cuál es la edad que divide a los pasajeros en dos grupos iguales?»

In [ ]:
df["Age"].median()

28.0

### `min()` — Mínimo

> **¿Para qué le sirve al analista?** Permite conocer el menor valor registrado.
>
> **Pregunta:** «¿Cuál era la edad del pasajero más joven?»

In [ ]:
df["Age"].min()

0.42

### `max()` — Máximo

> **¿Para qué le sirve al analista?** Permite conocer el mayor valor registrado.
>
> **Pregunta:** «¿Cuál era la edad del pasajero más anciano?»

In [ ]:
df["Age"].max()

80.0

### `sum()` — Suma

> **¿Para qué le sirve al analista?** Permite obtener el total acumulado de una variable numérica. Por ejemplo: «¿Cuánto dinero recaudó el Titanic en billetes?»

In [ ]:
df["Fare"].sum()

np.float64(28693.9493)

### `std()` — Desviación estándar

> **¿Para qué le sirve al analista?** Permite estudiar la dispersión de los valores alrededor del promedio. Una desviación estándar grande indica mayor variabilidad.

In [ ]:
df["Age"].std()

14.526497332334044

## `value_counts()`

Una función fundamental para variables categóricas.

> **¿Para qué le sirve al analista?** Permite conocer la frecuencia de aparición de cada categoría. Esto es fundamental cuando trabajamos con variables categóricas.
>
> **Pregunta de negocio:** «¿Cuántos hombres y mujeres viajaban en el Titanic?»

In [ ]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

### `value_counts(normalize=True)`

Devuelve frecuencias relativas. Podemos multiplicar por 100 para obtener porcentajes.

> **¿Para qué le sirve al analista?** Permite pasar de cantidades absolutas a porcentajes. Por ejemplo: «El 64.8 % de los pasajeros eran hombres y el 35.2 % mujeres.» Esto suele ser mucho más fácil de interpretar en un informe.

In [ ]:
df["Sex"].value_counts(normalize=True) * 100

Sex
male      64.758698
female    35.241302
Name: proportion, dtype: float64

## `unique()`

> **¿Para qué le sirve al analista?** Permite descubrir qué valores diferentes existen dentro de una variable. Por ejemplo: «¿Qué puertos de embarque aparecen en nuestro dataset?»

In [ ]:
df["Embarked"].unique()

array(['S', 'C', 'Q', nan], dtype=object)

## `nunique()`

> **¿Para qué le sirve al analista?** Permite conocer la cardinalidad de una variable categórica. Por ejemplo: «¿Cuántos puertos de embarque diferentes hay?»

In [ ]:
df["Embarked"].nunique()

3

## Filtrar datos

Una de las tareas más importantes del análisis de datos es seleccionar solamente los registros que cumplen determinadas condiciones. Por ejemplo, pasajeros mayores de 40 años.

> **¿Para qué le sirve al analista?** Permite concentrar el análisis en un subconjunto específico de los datos.
>
> **Pregunta:** «¿Qué pasajeros tenían más de 40 años?»

In [ ]:
df[df["Age"] > 40]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

### Crear una condición

Podemos guardar la condición en una variable, lo que hace explícito el concepto de **máscara booleana**.

In [ ]:
filtro = df["Age"] > 40
df[filtro]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

### Filtrar por igualdad

> **¿Para qué le sirve al analista?** Permite analizar exclusivamente un grupo determinado.
>
> **Pregunta:** «¿Cómo eran las pasajeras mujeres?»

In [ ]:
df[df["Sex"] == "female"]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

### Filtrar valores mayores

> **¿Para qué le sirve al analista?** Permite localizar pasajeros que pagaron tarifas elevadas.
>
> **Pregunta:** «¿Qué pasajeros pagaron más de 100 dólares?»

In [ ]:
df[df["Fare"] > 100]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss. Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss. Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss. Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss. Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss. Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss. Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss. Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss. Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

### Filtrar utilizando varias condiciones (AND)

Podemos combinar condiciones utilizando `&`. Esto significa: «Edad mayor a 40 Y tarifa superior a 100.»

> **¿Para qué le sirve al analista?** Permite construir consultas más específicas.
>
> **Pregunta:** «¿Qué pasajeros mayores de 40 años pagaron más de 100 dólares?»

In [ ]:
df[
    (df["Age"] > 40) &
    (df["Fare"] > 100)
]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,PC 17582,153.4625,C125,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.0,0,0,16966,134.5000,E40,C
380,381,1,1,"Bidois, Miss. Rosalie",female,42.0,0,0,PC 17757,227.5250,NaN,C
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.0,1,0,PC 17761,106.4250,C86,C
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.0,2,0,PC 17611,133.6500,NaN,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.0,1,1,17421,110.8833,C68,C
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.0,0,1,24160,211.3375,B3,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S

### OR

Podemos utilizar `|`. Esto significa: «Embarque en Cherbourg O en Queenstown.»

> **¿Para qué le sirve al analista?** Permite analizar grupos formados por diferentes categorías.

In [ ]:
df[
    (df["Embarked"] == "C") |
    (df["Embarked"] == "Q")
]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### `isin()`

Cuando queremos seleccionar varias categorías.

> **¿Para qué le sirve al analista?** Hace que las consultas sobre múltiples categorías sean más claras y legibles.

In [ ]:
df[
    df["Embarked"].isin(["C", "Q", "S"])
]

,id,sobrevivido,clase,Name,sexo,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025,Edad_diferencia,AgeGroup,FareCategory
0,1,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False,942.500,-7.699118,Adulto,NaN
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,False,9266.829,8.300882,Adulto,NaN
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False,1030.250,-3.699118,Adulto,NaN
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False,6903.000,5.300882,Adulto,NaN
4,5,False,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False,1046.500,5.300882,Adulto,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,False,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,False,1690.000,-2.699118,Adulto,NaN
887,888,True,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,False,3900.000,-10.699118,Adulto,NaN
888,889,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,False,3048.500,NaN,Adulto,NaN
889,890,True,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,False,3900.000,-3.699118,Adulto,NaN
890,891,False,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,False,1007.500,2.300882,Adulto,NaN

### Filtrar por rango

> **¿Para qué le sirve al analista?** Permite estudiar segmentos específicos de una población.
>
> **Pregunta:** «¿Cómo eran los pasajeros de entre 20 y 30 años?»

In [ ]:
df[
    (df["Age"] >= 20) &
    (df["Age"] <= 30)
]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

## Ordenar datos

`sort_values()` ordena el DataFrame según una columna (por defecto, de menor a mayor).

> **¿Para qué le sirve al analista?** Permite organizar los datos para identificar rápidamente valores pequeños, valores grandes, mejores resultados o peores resultados.

In [ ]:
df.sort_values("Fare")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S
413,414,0,2,"Cunningham, Mr. Alfred Fleming",male,NaN,0,0,239853,0.0000,NaN,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0000,NaN,S
302,303,0,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C

### Orden descendente

> **¿Para qué le sirve al analista?** Permite colocar primero los valores más altos. Por ejemplo: «¿Cuáles son los pasajeros que pagaron las tarifas más altas?»

In [ ]:
df.sort_values(
    "Fare",
    ascending=False
)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
...,...,...,...,...,...,...,...,...,...,...,...,...
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0000,NaN,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0000,NaN,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0000,NaN,S

### Seleccionar los primeros resultados

Podemos combinar `sort_values()` con `head()`. Este patrón es muy frecuente en análisis: **ordenar → seleccionar los primeros registros**.

> **¿Para qué le sirve al analista?** Permite encontrar rápidamente los 10 pasajeros con mayor tarifa.

In [ ]:
df.sort_values(
    "Fare",
    ascending=False
).head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C

## Crear nuevas columnas

Pandas permite crear variables derivadas. Por ejemplo, una columna que indique si el pasajero es niño (menor de 18 años).

> **¿Para qué le sirve al analista?** Permite crear variables que no existían originalmente, pero que son útiles para el análisis: categorías de edad, tamaño del grupo familiar, indicadores de supervivencia, tarifas en otra moneda, etc.

In [ ]:
df["IsChild"] = df["Age"] < 18
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,False
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,False
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,False
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,False

## Operaciones vectorizadas

Una de las ventajas de Pandas es que podemos aplicar operaciones a una columna completa, sin necesidad de recorrer cada fila mediante un `for`.

> **¿Para qué le sirve al analista?** Permite transformar grandes cantidades de datos de manera compacta y eficiente.

In [ ]:
df["Fare"] * 1.1

0       7.97500
1      78.41163
2       8.71750
3      58.41000
4       8.85500
         ...
886    14.30000
887    33.00000
888    25.79500
889    33.00000
890     8.52500
Name: Fare, Length: 891, dtype: float64

In [ ]:
# Operación vectorizada con un escalar (factor de inflación)

# Pandas toma el escalar 130 y lo multiplica por cada uno de los 891 precios
# de la columna Fare simultáneamente. Un pasajero que pagó £7 en 1912, ahora
# verá £910 en la nueva columna.
df["Fare_2025"] = df["Fare"] * 130
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False,942.500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,False,9266.829
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False,1030.250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False,6903.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False,1046.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,False,1690.000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,False,3900.000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,False,3048.500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,False,3900.000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,False,1007.500

In [ ]:
# Operación vectorizada: restar la media de toda la columna a cada valor

# Pandas calcula la media de toda la columna Age (un solo número) y lo resta
# de cada uno de los 891 valores de edad al mismo tiempo. Obtienes una columna
# nueva con valores como -5.2 (más joven que el promedio) o +8.7 (más viejo).

df["Edad_diferencia"] = df["Age"] - df["Age"].mean()
df

,id,sobrevivido,clase,Name,sexo,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025,Edad_diferencia,AgeGroup,FareCategory
0,1,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False,942.500,-7.699118,Adulto,NaN
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,False,9266.829,8.300882,Adulto,NaN
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False,1030.250,-3.699118,Adulto,NaN
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False,6903.000,5.300882,Adulto,NaN
4,5,False,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False,1046.500,5.300882,Adulto,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,False,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,False,1690.000,-2.699118,Adulto,NaN
887,888,True,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,False,3900.000,-10.699118,Adulto,NaN
888,889,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,False,3048.500,NaN,Adulto,NaN
889,890,True,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,False,3900.000,-3.699118,Adulto,NaN
890,891,False,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,False,1007.500,2.300882,Adulto,NaN

## Crear categorías

Supongamos que queremos clasificar a los pasajeros por rango de edad.

> **¿Para qué le sirve al analista?** Permite transformar valores numéricos en categorías útiles para el análisis (niño, adulto, senior), lo que facilita posteriormente la segmentación.

In [ ]:
df["AgeGroup"] = "Adulto"

df.loc[
    df["Age"] < 18,
    "AgeGroup"
] = "Niño"

df.loc[
    df["Age"] >= 60,
    "AgeGroup"
] = "Anciano"

## `loc[]`

`loc[]` permite seleccionar datos utilizando etiquetas y condiciones.

> **¿Para qué le sirve al analista?** Permite seleccionar simultáneamente determinadas filas y determinadas columnas. Es especialmente útil cuando queremos realizar operaciones sobre un subconjunto específico del DataFrame.

In [ ]:
df.loc[
    df["Age"] > 40,
    ["Name", "Age", "Fare"]
]

                                                  Name   Age     Fare
6                              McCarthy, Mr. Timothy J  54.0  51.8625
11                            Bonnell, Miss. Elizabeth  58.0  26.5500
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0  16.0000
33                               Wheadon, Mr. Edward H  66.0  10.5000
35                      Holverson, Mr. Alexander Oskar  42.0  52.0000
..                                                 ...   ...      ...
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  48.0  25.9292
865                           Bystrom, Mrs. (Karolina)  42.0  13.0000
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0  52.5542
873                        Vander Cruyssen, Mr. Victor  47.0   9.0000
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0  83.1583

[150 rows x 3 columns]

### Modificar datos utilizando `loc`

> **¿Para qué le sirve al analista?** Permite modificar datos de forma controlada según una condición. Esto aparece frecuentemente en procesos de limpieza y transformación de datos.

In [ ]:
df.loc[
    df["Fare"] > 200,
    "FareCategory"
] = "Muy alta"

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025,Edad_diferencia,AgeGroup,FareCategory
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False,942.500,-7.699118,Adulto,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,False,9266.829,8.300882,Adulto,NaN
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False,1030.250,-3.699118,Adulto,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False,6903.000,5.300882,Adulto,NaN
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False,1046.500,5.300882,Adulto,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,False,1690.000,-2.699118,Adulto,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,False,3900.000,-10.699118,Adulto,NaN
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,False,3048.500,NaN,Adulto,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,False,3900.000,-3.699118,Adulto,NaN
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,False,1007.500,2.300882,Adulto,NaN

## `isna()`

Una tarea fundamental antes de analizar datos es comprobar si existen valores faltantes. `isna()` devuelve valores booleanos.

In [ ]:
df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025,Edad_diferencia,AgeGroup,FareCategory
0,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
888,False,False,False,False,False,True,False,False,False,False,True,False,False,False,True,False,True
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
890,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True

### Contar valores faltantes

En el Titanic veremos que `Age`, `Cabin` y `Embarked` tienen faltantes.

> **¿Para qué le sirve al analista?** Los valores faltantes pueden afectar los resultados del análisis. Antes de calcular estadísticas o construir modelos debemos saber: «¿Hay información faltante? ¿En qué variables? ¿Cuántos valores faltan?»

In [ ]:
df.isna().sum()

PassengerId          0
Survived             0
Pclass               0
Name                 0
Sex                  0
Age                177
SibSp                0
Parch                0
Ticket               0
Fare                 0
Cabin              687
Embarked             2
IsChild              0
Fare_2025            0
Edad_diferencia    177
AgeGroup             0
FareCategory       871
dtype: int64

## `notna()`

> **¿Para qué le sirve al analista?** Permite construir filtros basados en la presencia de información.

In [ ]:
df.notna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025,Edad_diferencia,AgeGroup,FareCategory
0,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,False
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
2,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,False
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
4,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,False
887,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
888,True,True,True,True,True,False,True,True,True,True,False,True,True,True,False,True,False
889,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False
890,True,True,True,True,True,True,True,True,True,True,False,True,True,True,True,True,False

## Eliminar valores faltantes

`dropna()` elimina filas que contienen valores faltantes.

> **¿Para qué le sirve al analista?** Puede ser útil cuando los registros incompletos no son necesarios para determinado análisis.
>
> ⚠️ **Advertencia importante:** no debemos eliminar valores faltantes automáticamente. Primero debemos comprender por qué faltan, cuántos faltan y si eliminarlos puede afectar el análisis.

In [ ]:
df.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025,Edad_diferencia,AgeGroup,FareCategory
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,False,34190.000,-10.699118,Adulto,Muy alta
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,False,34190.000,-6.699118,Adulto,Muy alta
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C,False,32177.704,-5.699118,Adulto,Muy alta
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C,False,32177.704,20.300882,Adulto,Muy alta
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,False,34108.750,-11.699118,Adulto,Muy alta
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S,False,34190.000,-5.699118,Adulto,Muy alta
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.0,0,2,113503,211.5000,C82,C,False,27495.000,-2.699118,Adulto,Muy alta
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,False,34190.000,34.300882,Anciano,Muy alta
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,False,66602.796,6.300882,Adulto,Muy alta
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.0,0,1,24160,211.3375,B5,S,True,27473.875,-14.699118,Niño,Muy alta
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0,1,0,PC 17757,227.5250,C62 C64,C,False,29578.250,-11.699118,Adulto,Muy alta
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.0,0,0,PC 17757,227.5250,C45,C,False,29578.250,8.300882,Adulto,Muy alta
730,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,False,27473.875,-0.699118,Adulto,Muy alta
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,False,66602.796,5.300882,Adulto,Muy alta
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,False,34108.750,-8.699118,Adulto,Muy alta
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.0,0,1,24160,211.3375,B3,S,False,27473.875,13.300882,Adulto,Muy alta

## Reemplazar valores faltantes

`fillna()` reemplaza valores faltantes, por ejemplo por el promedio de edad.

> **¿Para qué le sirve al analista?** Permite conservar registros que de otra forma podrían perderse. Sin embargo, la estrategia adecuada depende del contexto: no siempre debemos reemplazar un dato faltante por la media.

In [ ]:
df["Age"].fillna(
    df["Age"].mean()
)

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

## `groupby()`

Una de las funciones más importantes de Pandas: permite dividir los datos en grupos según una variable.

```
Todos los pasajeros
        ↓
-------------------
Hombre
Mujer
```

> **¿Para qué le sirve al analista?** Permite comparar el comportamiento de una métrica entre diferentes grupos. Esta es una de las operaciones más importantes del análisis de datos.
>
> **Pregunta:** «¿Cómo se comporta la supervivencia según el sexo?»

In [ ]:
df.groupby("Sex")

### `groupby()` + `mean()`

> **¿Para qué le sirve al analista?** Permite comparar la tasa de supervivencia entre grupos.
>
> **Pregunta de negocio:** «¿Las mujeres tenían más probabilidades de sobrevivir que los hombres?»

In [ ]:
df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

### `groupby()` + `sum()`

> **¿Para qué le sirve al analista?** Permite conocer cuántos sobrevivieron en cada grupo.
>
> **Pregunta:** «¿Cuántas mujeres y cuántos hombres sobrevivieron?»

In [ ]:
df.groupby("Sex")["Survived"].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

### `groupby()` + `count()`

> **¿Para qué le sirve al analista?** Permite conocer la cantidad de personas en cada categoría.

In [ ]:
df.groupby("Sex")["PassengerId"].count()

Sex
female    314
male      577
Name: PassengerId, dtype: int64

### `groupby()` + múltiples estadísticas

> **¿Para qué le sirve al analista?** Permite construir un perfil estadístico de cada categoría, y comparar grupos desde diferentes perspectivas.

In [ ]:
df.groupby("Sex")["Fare"].agg(
    ["count", "mean", "min", "max", "sum"]
)

        count       mean   min       max         sum
Sex
female    314  44.479818  6.75  512.3292  13966.6628
male      577  25.523893  0.00  512.3292  14727.2865

In [ ]:
# Ejemplo más flexible en donde obtenemos las estadísticas distintas
# para Fare y para Age en la misma tabla.

df.groupby("Sex").agg({
    "Fare": ["mean", "max"],
    "Age": ["mean", "min"]
})

             Fare                  Age
             mean       max       mean   min
Sex
female  44.479818  512.3292  27.915709  0.75
male    25.523893  512.3292  30.726645  0.42

### Agrupaciones múltiples

También podemos agrupar utilizando más de una variable.

> **¿Para qué le sirve al analista?** Permite detectar diferencias más específicas.
>
> **Pregunta:** «¿Cuál es la tasa de supervivencia según sexo y clase?» Este tipo de análisis comienza a acercarnos a preguntas más interesantes.

In [ ]:
df.groupby(
    ["Sex", "Pclass"]
)["Survived"].mean()

Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: Survived, dtype: float64

## `crosstab`

Genera una tabla de frecuencias cruzadas.

> **¿Para qué le sirve al analista?** Permite comparar dos variables categóricas.
>
> **Pregunta:** «¿Cómo se distribuyen los sobrevivientes según el sexo?»

In [ ]:
pd.crosstab(
    df["Sex"],
    df["Survived"]
)

Survived    0    1
Sex
female     81  233
male      468  109

## Tablas dinámicas (pivot tables)

> **¿Para qué le sirve al analista?** Una tabla dinámica permite resumir información de manera muy flexible. Es conceptualmente similar a una tabla dinámica de Excel, pero construida mediante código.

In [ ]:
pd.pivot_table(
    df,
    values="Fare",
    index="Pclass",
    aggfunc="mean"
)

             Fare
Pclass
1       84.154687
2       20.662183
3       13.675550

## Analizar la supervivencia

> **¿Para qué le sirve al analista?** Permite saber cuántos sobrevivieron y cuántos no.
>
> **Pregunta:** «¿Cuántos pasajeros sobrevivieron al Titanic?»

In [ ]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

### Supervivencia por clase

> **¿Para qué le sirve al analista?** Permite determinar si la clase influyó en la supervivencia.
>
> **Pregunta:** «¿Los pasajeros de primera clase tuvieron mayor tasa de supervivencia?»

In [ ]:
df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

### Tarifa promedio por clase

> **¿Para qué le sirve al analista?** Permite conocer el costo promedio de cada clase.
>
> **Pregunta:** «¿Cuánto pagaron en promedio los pasajeros de cada clase?»

In [ ]:
df.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

### Múltiples métricas por clase

Ahora podemos comparar cantidad de pasajeros, tarifa promedio y recaudación total por clase.

In [ ]:
df.groupby("Pclass")["Fare"].agg(
    ["count", "mean", "sum"]
)

        count       mean         sum
Pclass
1         216  84.154687  18177.4125
2         184  20.662183   3801.8417
3         491  13.675550   6714.6951

## Analizar el puerto de embarque

Estamos pasando progresivamente de «¿Qué puertos existen?» a «¿Cuántos pasajeros embarcaron en cada uno?», luego «¿Cuánto pagaron en promedio?» y finalmente «¿Cuál fue la tasa de supervivencia según el puerto?»

> **Idea central:** «El análisis de datos no consiste solamente en ejecutar funciones. Consiste en formular preguntas y utilizar las herramientas adecuadas para responderlas.»

In [ ]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [ ]:
df.groupby("Embarked")["Fare"].mean()

Embarked
C    59.954144
Q    13.276030
S    27.079812
Name: Fare, dtype: float64

In [ ]:
df.groupby("Embarked")["Survived"].mean()

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64

## Renombrar columnas

> **¿Para qué le sirve al analista?** Permite utilizar nombres más cortos, consistentes y fáciles de programar. Esto mejora la legibilidad del código.

In [ ]:
df = df.rename(
    columns={
        "PassengerId": "id",
        "Survived": "sobrevivido",
        "Pclass": "clase",
        "Sex": "sexo"
    }
)

## Convertir tipos

> **¿Para qué le sirve al analista?** Los tipos de datos correctos permiten realizar operaciones apropiadas. Por ejemplo, convertir `Survived` a booleano facilita el cálculo de proporciones.

> ⚠️ Nota: como en la celda anterior renombramos `Survived` a `sobrevivido`, ajustamos el nombre de columna aquí.

In [ ]:
df["sobrevivido"] = df["sobrevivido"].astype(bool)
df

,id,sobrevivido,clase,Name,sexo,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025,Edad_diferencia,AgeGroup,FareCategory
0,1,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False,942.500,-7.699118,Adulto,NaN
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,False,9266.829,8.300882,Adulto,NaN
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False,1030.250,-3.699118,Adulto,NaN
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False,6903.000,5.300882,Adulto,NaN
4,5,False,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False,1046.500,5.300882,Adulto,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,False,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,False,1690.000,-2.699118,Adulto,NaN
887,888,True,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,False,3900.000,-10.699118,Adulto,NaN
888,889,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,False,3048.500,NaN,Adulto,NaN
889,890,True,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,False,3900.000,-3.699118,Adulto,NaN
890,891,False,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,False,1007.500,2.300882,Adulto,NaN

## Aplicar funciones

`apply()` permite aplicar una función a los valores de una columna.

> **¿Para qué le sirve al analista?** Es útil cuando necesitamos realizar una transformación que no puede expresarse fácilmente mediante una operación vectorizada estándar. Sin embargo, cuando existe una operación vectorizada equivalente, normalmente conviene preferirla.

In [ ]:
df["Fare"].apply(
    lambda x: x * 1.1
)

0       7.97500
1      78.41163
2       8.71750
3      58.41000
4       8.85500
         ...
886    14.30000
887    33.00000
888    25.79500
889    33.00000
890     8.52500
Name: Fare, Length: 891, dtype: float64

## Detectar duplicados

> **¿Para qué le sirve al analista?** Los registros duplicados pueden provocar que determinadas estadísticas estén sesgadas. Antes de analizar un dataset es importante comprobar la calidad de los datos.
>
> **Pregunta:** «¿Tengo pasajeros repetidos?»

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

## Eliminar duplicados

> **¿Para qué le sirve al analista?** Permite eliminar registros repetidos cuando sabemos que realmente representan duplicaciones. Nuevamente: no debemos eliminar datos sin comprender primero el problema.

In [ ]:
df.drop_duplicates()

,id,sobrevivido,clase,Name,sexo,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025,Edad_diferencia,AgeGroup,FareCategory
0,1,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False,942.500,-7.699118,Adulto,NaN
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,False,9266.829,8.300882,Adulto,NaN
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False,1030.250,-3.699118,Adulto,NaN
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False,6903.000,5.300882,Adulto,NaN
4,5,False,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False,1046.500,5.300882,Adulto,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,False,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,False,1690.000,-2.699118,Adulto,NaN
887,888,True,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,False,3900.000,-10.699118,Adulto,NaN
888,889,False,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,False,3048.500,NaN,Adulto,NaN
889,890,True,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,False,3900.000,-3.699118,Adulto,NaN
890,891,False,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,False,1007.500,2.300882,Adulto,NaN

---

## Ejemplo con duplicados

In [ ]:
import pandas as pd
import numpy as np

# Generamos 50 valores de ejemplo
data = {
    "ID": np.arange(1, 51),
    "Name": ["Persona_" + str(i) for i in range(1, 51)],
    "Age": np.random.randint(18, 60, size=50)
}
df_person = pd.DataFrame(data)

# Introducimos duplicados (copiamos algunas filas)
df_person = pd.concat([df_person, df_person.iloc[10:15], df_person.iloc[20:22]], ignore_index=True)

print("Cantidad de filas con duplicados:", len(df))
df_person

Cantidad de filas con duplicados: 891

    ID        Name  Age
0    1   Persona_1   58
1    2   Persona_2   29
2    3   Persona_3   57
3    4   Persona_4   36
4    5   Persona_5   47
5    6   Persona_6   22
6    7   Persona_7   41
7    8   Persona_8   51
8    9   Persona_9   48
9   10  Persona_10   21
10  11  Persona_11   54
11  12  Persona_12   32
12  13  Persona_13   58
13  14  Persona_14   56
14  15  Persona_15   55
15  16  Persona_16   29
16  17  Persona_17   48
17  18  Persona_18   58
18  19  Persona_19   46
19  20  Persona_20   21
20  21  Persona_21   20
21  22  Persona_22   18
22  23  Persona_23   22
23  24  Persona_24   59
24  25  Persona_25   22
25  26  Persona_26   24
26  27  Persona_27   41
27  28  Persona_28   23
28  29  Persona_29   23
29  30  Persona_30   38
30  31  Persona_31   49
31  32  Persona_32   20
32  33  Persona_33   36
33  34  Persona_34   26
34  35  Persona_35   28
35  36  Persona_36   33
36  37  Persona_37   45
37  38  Persona_38   33
38  39  Persona_39   59
39  40  Persona_40   40
40  41  Persona_41   33
41  42  Persona_42   21
42  43  Persona_43   58
43  44  Persona_44   46
44  45  Persona_45   23
45  46  Persona_46   53
46  47  Persona_47   18
47  48  Persona_48   21
48  49  Persona_49   48
49  50  Persona_50   58
50  11  Persona_11   54
51  12  Persona_12   32
52  13  Persona_13   58
53  14  Persona_14   56
54  15  Persona_15   55
55  21  Persona_21   20
56  22  Persona_22   18

In [ ]:
# Detectar duplicados
df_person.duplicated().sum() # Esto nos dice cuántas filas están repetidas.

np.int64(7)

In [ ]:
# Eliminar duplicados
df_clean = df_person.drop_duplicates()
print("Cantidad de filas después de limpiar:", len(df_clean))

# Ahora el DataFrame vuelve a tener solo las filas únicas.
df_person

Cantidad de filas después de limpiar: 50

    ID        Name  Age
0    1   Persona_1   58
1    2   Persona_2   29
2    3   Persona_3   57
3    4   Persona_4   36
4    5   Persona_5   47
5    6   Persona_6   22
6    7   Persona_7   41
7    8   Persona_8   51
8    9   Persona_9   48
9   10  Persona_10   21
10  11  Persona_11   54
11  12  Persona_12   32
12  13  Persona_13   58
13  14  Persona_14   56
14  15  Persona_15   55
15  16  Persona_16   29
16  17  Persona_17   48
17  18  Persona_18   58
18  19  Persona_19   46
19  20  Persona_20   21
20  21  Persona_21   20
21  22  Persona_22   18
22  23  Persona_23   22
23  24  Persona_24   59
24  25  Persona_25   22
25  26  Persona_26   24
26  27  Persona_27   41
27  28  Persona_28   23
28  29  Persona_29   23
29  30  Persona_30   38
30  31  Persona_31   49
31  32  Persona_32   20
32  33  Persona_33   36
33  34  Persona_34   26
34  35  Persona_35   28
35  36  Persona_36   33
36  37  Persona_37   45
37  38  Persona_38   33
38  39  Persona_39   59
39  40  Persona_40   40
40  41  Persona_41   33
41  42  Persona_42   21
42  43  Persona_43   58
43  44  Persona_44   46
44  45  Persona_45   23
45  46  Persona_46   53
46  47  Persona_47   18
47  48  Persona_48   21
48  49  Persona_49   48
49  50  Persona_50   58
50  11  Persona_11   54
51  12  Persona_12   32
52  13  Persona_13   58
53  14  Persona_14   56
54  15  Persona_15   55
55  21  Persona_21   20
56  22  Persona_22   18

---

## Selección por posición: `iloc`

Pandas también permite seleccionar datos utilizando posiciones numéricas.

> **¿Para qué le sirve al analista?** `iloc` resulta útil cuando queremos trabajar utilizando posiciones, independientemente de las etiquetas.

### Diferencia entre `loc` e `iloc`

- **`loc`** → trabaja principalmente con etiquetas y condiciones
- **`iloc`** → trabaja con posiciones

Una forma sencilla de recordarlo: `loc` → etiquetas, `iloc` → posiciones.

In [ ]:
df.iloc[0]

id                                       1
sobrevivido                          False
clase                                    3
Name               Braund, Mr. Owen Harris
sexo                                  male
Age                                   22.0
SibSp                                    1
Parch                                    0
Ticket                           A/5 21171
Fare                                  7.25
Cabin                                  NaN
Embarked                                 S
IsChild                              False
Fare_2025                            942.5
Edad_diferencia                  -7.699118
AgeGroup                            Adulto
FareCategory                           NaN
Name: 0, dtype: object

In [ ]:
df.iloc[0:5]

,id,sobrevivido,clase,Name,sexo,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025,Edad_diferencia,AgeGroup,FareCategory
0,1,False,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False,942.500,-7.699118,Adulto,NaN
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,False,9266.829,8.300882,Adulto,NaN
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False,1030.250,-3.699118,Adulto,NaN
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False,6903.000,5.300882,Adulto,NaN
4,5,False,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False,1046.500,5.300882,Adulto,NaN

## Exportar resultados

Después de realizar un análisis podemos guardar un DataFrame.

> **¿Para qué le sirve al analista?** Permite guardar los resultados para compartirlos, utilizarlos posteriormente, generar informes o alimentar otras herramientas.

In [ ]:
df.to_csv("titanic_completo_procesado.csv", index=False)
print("¡DataFrame completo guardado!")

# index=False --> Le dice a Pandas: "No guardes la columna de la izquierda con los números de fila (el índice)".
# Si no pones eso, el archivo CSV tendrá una columna extra de números (0, 1, 2...) que casi nunca necesitamos.

¡DataFrame completo guardado!

In [ ]:
# Muestra todas las variables que hemos creado hasta el momento
%whos

Variable    Type         Data/Info
----------------------------------
data        dict         n=3
df          DataFrame          id  sobrevivido  cl<...>\n[891 rows x 17 columns]
df_clean    DataFrame        ID        Name  Age\n<...>\n49  50  Persona_50   58
df_person   DataFrame        ID        Name  Age\n<...>\n56  22  Persona_22   18
edad        Series       0      22.0\n1      38.0\<...>ngth: 891, dtype: float64
filtro      Series       0      False\n1      Fals<...> Length: 891, dtype: bool
np          module       <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
pd          module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
resultado   DataFrame                  count      <...>  male      347  0.135447

## El proceso completo de análisis

Un análisis típico puede seguir este flujo:

```
Cargar datos → Explorar → Comprender variables → Revisar calidad
    → Limpiar → Seleccionar → Filtrar → Transformar
    → Agrupar → Resumir → Comparar → Obtener conclusiones
```

Este flujo es mucho más importante que memorizar funciones individualmente.

---

# Ejemplo integrador con el Titanic

Supongamos que somos analistas de datos y queremos estudiar la tragedia del Titanic. La empresa (o el historiador) quiere comprender los factores que influyeron en la supervivencia.

**Pregunta 1: ¿Cuántos pasajeros viajaban en el Titanic?**

¿Para qué? Para conocer el tamaño de la muestra.

In [ ]:
df.shape[0]

891

**Pregunta 2: ¿Qué variables tenemos?**

¿Para qué? Para conocer qué información podemos utilizar.

In [ ]:
df.columns

Index(['id', 'sobrevivido', 'clase', 'Name', 'sexo', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked', 'IsChild', 'Fare_2025',
       'Edad_diferencia', 'AgeGroup', 'FareCategory'],
      dtype='object')

**Pregunta 3: ¿Cómo están estructurados los datos?**

¿Para qué? Para conocer tipos de datos y detectar posibles valores faltantes (edad, cabina, embarque).

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               891 non-null    int64
 1   sobrevivido      891 non-null    bool
 2   clase            891 non-null    int64
 3   Name             891 non-null    object
 4   sexo             891 non-null    object
 5   Age              714 non-null    float64
 6   SibSp            891 non-null    int64
 7   Parch            891 non-null    int64
 8   Ticket           891 non-null    object
 9   Fare             891 non-null    float64
 10  Cabin            204 non-null    object
 11  Embarked         889 non-null    object
 12  IsChild          891 non-null    bool
 13  Fare_2025        891 non-null    float64
 14  Edad_diferencia  714 non-null    float64
 15  AgeGroup         891 non-null    object
 16  FareCategory     20 non-null     object
dtypes: bool(2), float64(4), int64(4), object(7)
memory usage: 106.3+ KB

**Pregunta 4: ¿Cuántos sobrevivieron y cuántos no?**

¿Para qué? Para conocer la distribución de la variable objetivo.

In [ ]:
df["sobrevivido"].value_counts()

sobrevivido
False    549
True     342
Name: count, dtype: int64

**Pregunta 5: ¿Cuál fue la tasa de supervivencia global?**

¿Para qué? Para obtener una medida general.

In [ ]:
df["sobrevivido"].mean()

np.float64(0.3838383838383838)

**Pregunta 6: ¿Cuál es la edad promedio de los pasajeros?**

¿Para qué? Para conocer el perfil etario de los pasajeros.

In [ ]:
df["Age"].mean()

np.float64(29.69911764705882)

**Pregunta 7: ¿Cuál es la tarifa promedio pagada?**

¿Para qué? Para conocer el costo promedio del billete.

In [ ]:
df["Fare"].mean()

np.float64(32.204207968574636)

**Pregunta 8: ¿Cuál fue la tarifa más alta?**

¿Para qué? Para identificar el billete más caro.

In [ ]:
df["Fare"].max()

512.3292

**Pregunta 9: ¿Cuántos hombres y mujeres viajaban?**

¿Para qué? Para conocer la composición por sexo.

In [ ]:
df["sexo"].value_counts()

sexo
male      577
female    314
Name: count, dtype: int64

**Pregunta 10: ¿Cuál fue la tasa de supervivencia por sexo?**

¿Para qué? Para comparar la supervivencia entre hombres y mujeres.

In [ ]:
df.groupby("sexo")["sobrevivido"].mean()

sexo
female    0.742038
male      0.188908
Name: sobrevivido, dtype: float64

**Pregunta 11: ¿Cuál fue la tasa de supervivencia por clase?**

¿Para qué? Para analizar si la clase influyó en la supervivencia.

In [ ]:
df.groupby("clase")["sobrevivido"].mean()

clase
1    0.629630
2    0.472826
3    0.242363
Name: sobrevivido, dtype: float64

**Pregunta 12: ¿Cuál fue la tarifa promedio por clase?**

¿Para qué? Para ver la relación entre clase y tarifa.

In [ ]:
df.groupby("clase")["Fare"].mean()

clase
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

**Pregunta 13: ¿Qué pasajeros pagaron más de 100 dólares?**

¿Para qué? Para analizar a los pasajeros con billetes de alto valor.

In [ ]:
df[df["Fare"] > 100]

,id,sobrevivido,clase,Name,sexo,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025,Edad_diferencia,AgeGroup,FareCategory
27,28,False,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S,False,34190.000,-10.699118,Adulto,Muy alta
31,32,True,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C,False,19047.704,NaN,Adulto,NaN
88,89,True,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S,False,34190.000,-6.699118,Adulto,Muy alta
118,119,False,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C,False,32177.704,-5.699118,Adulto,Muy alta
195,196,True,1,"Lurette, Miss. Elise",female,58.00,0,0,PC 17569,146.5208,B80,C,False,19047.704,28.300882,Adulto,NaN
215,216,True,1,"Newell, Miss. Madeleine",female,31.00,1,0,35273,113.2750,D36,C,False,14725.750,1.300882,Adulto,NaN
258,259,True,1,"Ward, Miss. Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C,False,66602.796,5.300882,Adulto,Muy alta
268,269,True,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S,False,19950.125,28.300882,Adulto,NaN
269,270,True,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S,False,17632.329,5.300882,Adulto,NaN
297,298,False,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,True,19701.500,-27.699118,Niño,NaN
299,300,True,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C,False,32177.704,20.300882,Adulto,Muy alta
305,306,True,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,True,19701.500,-28.779118,Niño,NaN
306,307,True,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C,False,14414.829,NaN,Adulto,NaN
307,308,True,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C,True,14157.000,-12.699118,Niño,NaN
311,312,True,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,False,34108.750,-11.699118,Adulto,Muy alta
318,319,True,1,"Wick, Miss. Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S,False,21432.671,1.300882,Adulto,NaN
319,320,True,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C,False,17485.000,10.300882,Adulto,NaN
325,326,True,1,"Young, Miss. Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C,False,17632.329,6.300882,Adulto,NaN
332,333,False,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S,False,19950.125,8.300882,Adulto,NaN
334,335,True,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S,False,17374.500,NaN,Adulto,NaN
337,338,True,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C,False,17485.000,11.300882,Adulto,NaN
341,342,True,1,"Fortune, Miss. Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S,False,34190.000,-5.699118,Adulto,Muy alta
373,374,False,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C,False,17632.329,-7.699118,Adulto,NaN
377,378,False,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C,False,27495.000,-2.699118,Adulto,Muy alta
380,381,True,1,"Bidois, Miss. Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C,False,29578.250,12.300882,Adulto,Muy alta
390,391,True,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S,False,15600.000,6.300882,Adulto,NaN
393,394,True,1,"Newell, Miss. Marjorie",female,23.00,1,0,35273,113.2750,D36,C,False,14725.750,-6.699118,Adulto,NaN
435,436,True,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S,True,15600.000,-15.699118,Niño,NaN
438,439,False,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S,False,34190.000,34.300882,Anciano,Muy alta
498,499,False,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,False,19701.500,-4.699118,Adulto,NaN
505,506,False,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C,False,14157.000,-11.699118,Adulto,NaN
527,528,False,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S,False,28831.296,NaN,Adulto,Muy alta
537,538,True,1,"LeRoy, Miss. Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C,False,13835.250,0.300882,Adulto,NaN
544,545,False,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C,False,13835.250,20.300882,Adulto,NaN
550,551,True,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C,True,14414.829,-12.699118,Niño,NaN
557,558,False,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C,False,29578.250,NaN,Adulto,Muy alta
581,582,True,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C,False,14414.829,9.300882,Adulto,NaN
609,610,True,1,"Shutes, Miss. Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S,False,19950.125,10.300882,Adulto,NaN
659,660,False,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C,False,14725.750,28.300882,Adulto,NaN
660,661,True,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S,False,17374.500,20.300882,Adulto,NaN
679,680,True,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C,False,66602.796,6.300882,Adulto,Muy alta
689,690,True,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S,True,27473.875,-14.699118,Niño,Muy alta
698,699,False,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C,False,14414.829,19.300882,Adulto,NaN
700,701,True,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C,False,29578.250,-11.699118,Adulto,Muy alta
708,709,True,1,"Cleaver, Miss. Alice",female,22.00,0,0,113781,151.5500,NaN,S,False,19701.500,-7.699118,Adulto,NaN
716,717,True,1,"Endres, Miss. Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C,False,29578.250,8.300882,Adulto,Muy alta
730,731,True,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,False,27473.875,-0.699118,Adulto,Muy alta
737,738,True,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C,False,66602.796,5.300882,Adulto,Muy alta
742,743,True,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,False,34108.750,-8.699118,Adulto,Muy alta
763,764,True,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S,False,15600.000,6.300882,Adulto,NaN
779,780,True,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S,False,27473.875,13.300882,Adulto,Muy alta
802,803,True,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S,True,15600.000,-18.699118,Niño,NaN
856,857,True,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S,False,21432.671,15.300882,Adulto,NaN

**Pregunta 14: ¿Qué pasajeros eran mujeres y sobrevivieron?**

¿Para qué? Para estudiar el perfil de las sobrevivientes.

In [ ]:
df[(df["sexo"] == "female") & (df["sobrevivido"] == True)]

,id,sobrevivido,clase,Name,sexo,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025,Edad_diferencia,AgeGroup,FareCategory
1,2,True,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,False,9266.829,8.300882,Adulto,NaN
2,3,True,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False,1030.250,-3.699118,Adulto,NaN
3,4,True,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False,6903.000,5.300882,Adulto,NaN
8,9,True,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,False,1447.329,-2.699118,Adulto,NaN
9,10,True,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,True,3909.204,-15.699118,Niño,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,True,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C,False,3120.000,-1.699118,Adulto,NaN
875,876,True,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C,True,939.250,-14.699118,Niño,NaN
879,880,True,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,False,10810.579,26.300882,Adulto,NaN
880,881,True,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S,False,3380.000,-4.699118,Adulto,NaN
887,888,True,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,False,3900.000,-10.699118,Adulto,NaN

**Pregunta 15: ¿Cuál fue la tarifa promedio por sexo y clase?**

¿Para qué? Para ver si existen diferencias en tarifa según sexo y clase.

In [ ]:
df.groupby(["sexo", "clase"])["Fare"].mean()

sexo    clase
female  1        106.125798
        2         21.970121
        3         16.118810
male    1         67.226127
        2         19.741782
        3         12.661633
Name: Fare, dtype: float64

**Pregunta 16: ¿Qué pasajeros tenían menos de 18 años y sobrevivieron?**

¿Para qué? Para analizar la supervivencia de los niños.

In [ ]:
df[(df["Age"] < 18) & (df["sobrevivido"] == True)]

,id,sobrevivido,clase,Name,sexo,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,IsChild,Fare_2025,Edad_diferencia,AgeGroup,FareCategory
9,10,True,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C,True,3909.204,-15.699118,Niño,NaN
10,11,True,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S,True,2171.000,-25.699118,Niño,NaN
22,23,True,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q,True,1043.796,-14.699118,Niño,NaN
39,40,True,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C,True,1461.421,-15.699118,Niño,NaN
43,44,True,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C,True,5405.296,-26.699118,Niño,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,831,True,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.00,1,0,2659,14.4542,NaN,C,True,1879.046,-14.699118,Niño,NaN
831,832,True,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S,True,2437.500,-28.869118,Niño,NaN
853,854,True,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S,True,5122.000,-13.699118,Niño,NaN
869,870,True,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S,True,1447.329,-25.699118,Niño,NaN
875,876,True,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,NaN,C,True,939.250,-14.699118,Niño,NaN

**Pregunta 17: ¿Cuántos pasajeros embarcaron en cada puerto?**

¿Para qué? Para conocer la procedencia de los pasajeros.

In [ ]:
df["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

**Pregunta 18: ¿Cuál fue la tasa de supervivencia por puerto de embarque?**

¿Para qué? Para ver si el puerto de embarque tuvo relación con la supervivencia.

In [ ]:
df.groupby("Embarked")["sobrevivido"].mean()

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: sobrevivido, dtype: float64

## Un análisis un poco más completo

Podemos combinar varias operaciones. Por ejemplo, un resumen de supervivencia por clase y sexo, ordenado de mayor a menor tasa:

1. `groupby()` → agrupar por clase y sexo
2. `agg()` → calcular cantidad y tasa
3. `sort_values()` → ordenar los resultados

Esto representa mucho mejor cómo se utiliza Pandas en un análisis real.

In [ ]:
resultado = (
    df.groupby(["clase", "sexo"])
      ["sobrevivido"]
      .agg(["count", "mean"])
      .sort_values("mean", ascending=False)
)
resultado

              count      mean
clase sexo
1     female     94  0.968085
2     female     76  0.921053
3     female    144  0.500000
1     male      122  0.368852
2     male      108  0.157407
3     male      347  0.135447

## La diferencia entre programar y analizar

Saber Pandas no significa simplemente conocer muchas funciones. Por ejemplo, `df.mean()` es una operación. Pero un analista debería preguntarse:

- «¿Qué variable estoy promediando?»
- «¿Por qué necesito el promedio?»
- «¿Es una medida adecuada?»
- «¿Qué significa el resultado?»
- «¿Existe algún valor extremo que pueda distorsionarlo?»
- «¿Necesito compararlo con otro grupo?»

El objetivo final no es ejecutar código. El objetivo es **obtener información útil a partir de los datos**.

## Pandas como herramienta de Análisis Exploratorio de Datos

Una vez que dominamos estas operaciones podemos comenzar a realizar **EDA — Exploratory Data Analysis** (Análisis Exploratorio de Datos). El objetivo del EDA es comprender los datos antes de realizar análisis más avanzados.

```
Dataset → Exploración → Limpieza → Transformación
   → Filtrado → Agrupación → Estadística descriptiva → EDA
```

Posteriormente podemos complementar Pandas con:

- **Matplotlib** → visualización
- **Seaborn** → visualización estadística
- **NumPy** → cálculo numérico
- **scikit-learn** → Machine Learning

## Resumen de funciones fundamentales (aplicado al Titanic)

| Función / propiedad | ¿Qué hace? | ¿Para qué le sirve al analista? |
|---|---|---|
| `pd.read_csv()` | Carga un CSV | Incorporar los datos al análisis |
| `head()` | Primeras filas | Explorar rápidamente |
| `tail()` | Últimas filas | Revisar el final del dataset |
| `shape` | Filas y columnas | Conocer el tamaño |
| `columns` | Nombres de columnas | Conocer las variables |
| `info()` | Información general | Diagnosticar estructura y tipos |
| `dtypes` | Tipos de datos | Comprender cómo tratar variables |
| `describe()` | Estadísticas descriptivas | Obtener un resumen inicial |
| `mean()` | Promedio | Analizar tendencia central |
| `median()` | Mediana | Tendencia central con menor sensibilidad a extremos |
| `min()` | Mínimo | Encontrar el menor valor |
| `max()` | Máximo | Encontrar el mayor valor |
| `sum()` | Suma | Obtener totales |
| `std()` | Desviación estándar | Medir dispersión |
| `value_counts()` | Frecuencias | Analizar categorías |
| `unique()` | Valores únicos | Conocer categorías |
| `nunique()` | Cantidad de categorías | Medir cardinalidad |
| `sort_values()` | Ordenar | Encontrar extremos y rankings |
| `groupby()` | Agrupar | Comparar grupos |
| `agg()` | Varias agregaciones | Crear resúmenes |
| `isin()` | Buscar varios valores | Filtrar categorías |
| `loc[]` | Seleccionar por etiquetas/condiciones | Trabajar con subconjuntos |
| `iloc[]` | Seleccionar por posición | Acceder por posición |
| `isna()` | Detectar faltantes | Evaluar calidad |
| `fillna()` | Reemplazar faltantes | Completar datos |
| `dropna()` | Eliminar faltantes | Limpiar registros |
| `duplicated()` | Detectar duplicados | Controlar calidad |
| `drop_duplicates()` | Eliminar duplicados | Limpiar datos |
| `rename()` | Cambiar nombres | Mejorar estructura y legibilidad |
| `astype()` | Cambiar tipos | Preparar variables |
| `to_csv()` | Exportar datos | Guardar resultados |

## Hilo conductor de la clase

```
DataFrame (Titanic) → Conocer los datos → Explorar → Seleccionar variables
   → Filtrar registros → Transformar datos → Analizar frecuencias
   → Agrupar → Calcular estadísticas → Comparar grupos
   → Obtener información → Responder preguntas de negocio
```

**Idea central:** «Pandas permite transformar un dataset en información que podemos utilizar para responder preguntas.»

## Idea final

Aprender Pandas no consiste en memorizar una lista de funciones. Lo importante es aprender a pensar el proceso:

```
¿Qué quiero saber?
        ↓
¿Qué variable necesito?
        ↓
¿Qué registros necesito analizar?
        ↓
¿Necesito filtrar?
        ↓
¿Necesito agrupar?
        ↓
¿Qué estadística necesito?
        ↓
¿Cómo interpreto el resultado?
```

Este cambio de perspectiva es fundamental para una materia de Introducción al Análisis de Datos.

**El código es la herramienta.** La capacidad de formular preguntas, seleccionar información relevante, analizarla e interpretar los resultados es lo que convierte esos datos en conocimiento.